version: "3.9" # optional since v1.27.0
services:
  backend:
  image: /Courses/Udemy/nextjsinfluencer/react-admin/
  environment:
  DB_HOST: db
  DB_DATABASE: admin
  DB_USERNAME: root
  DB_PASSWORD: root
ports:
  - 8000:8000
depends_on:
  - db

db:
  image: mysql.5.7.22
  environment:
  MYSQL_DATABASE: admin
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_ROOT_PASSWORD: root

volumes:
  - .dbdata:/var/lib/mysql
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/code
#       - logvolume01:/var/log
#     links:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}
